/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec;

import org.junit.Test;
import static org.junit.Assert.*;

public class ShopTestTest {
    @Test public void appHasAGreeting() {
        Shop_test classUnderTest = new Shop_test();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
